# Generated by Django 5.2.8 on 2025-11-24 21:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="نام شبکه")),
                ("code", models.CharField(max_length=20, unique=True, verbose_name="کد شبکه")),
                (
                    "program_type",
                    models.CharField(
                        choices=[("radio", "رادیو"), ("tv", "تلویزیون")], max_length=10, verbose_name="نوع پخش"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ثبت")),
            ],
            options={
                "verbose_name": "شبکه",
                "verbose_name_plural": "شبکه\u200cها",
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="نام ژانر")),
                ("code", models.CharField(max_length=20, unique=True, verbose_name="کد ژانر")),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
            ],
            options={
                "verbose_name": "ژانر",
                "verbose_name_plural": "ژانرها",
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("full_name", models.CharField(max_length=150, verbose_name="نام کامل")),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="ایمیل")),
                ("phone", models.CharField(blank=True, max_length=20, verbose_name="تلفن")),
                ("bio", models.TextField(blank=True, verbose_name="بیوگرافی")),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ثبت")),
            ],
            options={
                "verbose_name": "فرد",
                "verbose_name_plural": "افراد",
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="نام نقش")),
                ("code", models.CharField(max_length=20, unique=True, verbose_name="کد نقش")),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
            ],
            options={
                "verbose_name": "نقش",
                "verbose_name_plural": "نقش\u200cها",
            },
        ),
        migrations.CreateModel(
            name="TargetAudience",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="نام دسته\u200cبندی")),
                (
                    "age_min",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(150),
                        ],
                        verbose_name="حداقل سن",
                    ),
                ),
                (
                    "age_max",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(150),
                        ],
                        verbose_name="حداکثر سن",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
            ],
            options={
                "verbose_name": "مخاطب هدف",
                "verbose_name_plural": "مخاطبین هدف",
            },
        ),
        migrations.CreateModel(
            name="Conductor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("auto_play_intro", models.BooleanField(default=True, verbose_name="پخش خودکار اپنینگ")),
                ("auto_play_outro", models.BooleanField(default=True, verbose_name="پخش خودکار انگلیزی")),
                ("auto_adjust_volume", models.BooleanField(default=False, verbose_name="تنظیم خودکار صدا")),
                ("auto_record", models.BooleanField(default=True, verbose_name="ضبط خودکار")),
                (
                    "priority",
                    models.IntegerField(
                        choices=[(1, "خیلی کم"), (2, "کم"), (3, "متوسط"), (4, "زیاد"), (5, "خیلی زیاد")],
                        default=3,
                        verbose_name="اولویت",
                    ),
                ),
                ("special_instructions", models.TextField(blank=True, verbose_name="دستورالعمل\u200cهای خاص")),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی")),
                (
                    "backup_program",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="programs.conductor",
                        verbose_name="برنامه جایگزین",
                    ),
                ),
                (
                    "contact_person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="programs.person",
                        verbose_name="شخص تماس",
                    ),
                ),
            ],
            options={
                "verbose_name": "کنداکتور",
                "verbose_name_plural": "کنداکتورها",
            },
        ),
        migrations.CreateModel(
            name="ConductorLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("start", "شروع"),
                            ("play_intro", "پخش اپنینگ"),
                            ("play_program", "پخش برنامه"),
                            ("play_outro", "پخش انگلیزی"),
                            ("pause", "توقف"),
                            ("resume", "ادامه"),
                            ("stop", "پایان"),
                            ("error", "خطا"),
                            ("manual_intervention", "مداخلهٔ دستی"),
                        ],
                        max_length=20,
                        verbose_name="اقدام",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "موفق"), ("failed", "ناموفق"), ("warning", "هشدار")],
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                ("message", models.TextField(verbose_name="پیام")),
                ("timestamp", models.DateTimeField(auto_now_add=True, verbose_name="زمان")),
                (
                    "conductor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="programs.conductor",
                        verbose_name="کنداکتور",
                    ),
                ),
            ],
            options={
                "verbose_name": "ثبت کنداکتور",
                "verbose_name_plural": "ثبت\u200cهای کنداکتور",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200, verbose_name="عنوان برنامه")),
                ("subtitle", models.CharField(blank=True, max_length=300, verbose_name="زیرعنوان")),
                ("description", models.TextField(verbose_name="توضیحات اصلی")),
                (
                    "default_duration",
                    models.IntegerField(
                        default=60,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1440),
                        ],
                        verbose_name="مدت زمان معمولی (دقیقه)",
                    ),
                ),
                ("is_live", models.BooleanField(default=False, verbose_name="برنامه زنده")),
                ("is_repeatable", models.BooleanField(default=False, verbose_name="قابل تکرار")),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                ("language", models.CharField(default="fa", max_length=10, verbose_name="زبان")),
                ("keywords", models.CharField(blank=True, max_length=500, verbose_name="کلمات کلیدی")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ثبت")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی")),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="programs.channel", verbose_name="شبکه"
                    ),
                ),
                ("genres", models.ManyToManyField(to="programs.genre", verbose_name="ژانرها")),
                ("target_audiences", models.ManyToManyField(to="programs.targetaudience", verbose_name="مخاطبین هدف")),
            ],
            options={
                "verbose_name": "برنامه",
                "verbose_name_plural": "برنامه\u200cها",
            },
        ),
        migrations.CreateModel(
            name="ProgramInstance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("episode_number", models.IntegerField(blank=True, null=True, verbose_name="شماره قسمت")),
                ("episode_title", models.CharField(blank=True, max_length=200, verbose_name="عنوان قسمت")),
                ("episode_description", models.TextField(blank=True, verbose_name="توضیحات قسمت")),
                ("scheduled_start", models.DateTimeField(verbose_name="زمان شروع برنامه\u200cریزی\u200cشده")),
                ("scheduled_end", models.DateTimeField(verbose_name="زمان پایان برنامه\u200cریزی\u200cشده")),
                ("actual_start", models.DateTimeField(blank=True, null=True, verbose_name="زمان شروع واقعی")),
                ("actual_end", models.DateTimeField(blank=True, null=True, verbose_name="زمان پایان واقعی")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودهٔ"),
                            ("pending", "در انتظار تایید"),
                            ("approved", "تایید\u200cشده"),
                            ("scheduled", "زمان\u200cبندی\u200cشده"),
                            ("broadcasting", "در حال پخش"),
                            ("completed", "تکمیل\u200cشده"),
                            ("cancelled", "لغو\u200cشده"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="یادداشت\u200cها")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ثبت")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی")),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instances",
                        to="programs.program",
                        verbose_name="برنامه",
                    ),
                ),
            ],
            options={
                "verbose_name": "نمونه برنامه",
                "verbose_name_plural": "نمونه\u200cهای برنامه",
                "ordering": ["-scheduled_start"],
            },
        ),
        migrations.CreateModel(
            name="ProgramAsset",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("intro", "اپنینگ"),
                            ("outro", "انگلیزی"),
                            ("audio", "فایل صوتی"),
                            ("video", "فایل تصویری"),
                            ("subtitle", "زیرنویس"),
                            ("thumbnail", "تصویر بند انگشتی"),
                            ("document", "سند"),
                            ("other", "سایر"),
                        ],
                        max_length=20,
                        verbose_name="نوع منبع",
                    ),
                ),
                ("file", models.FileField(upload_to="programs/assets/%Y/%m/%d/", verbose_name="فایل")),
                ("title", models.CharField(max_length=200, verbose_name="عنوان منبع")),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                ("duration", models.IntegerField(blank=True, null=True, verbose_name="مدت زمان (ثانیه)")),
                ("file_size", models.BigIntegerField(blank=True, null=True, verbose_name="حجم فایل (بایت)")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True, verbose_name="تاریخ آپلود")),
                (
                    "program_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="programs.programinstance",
                        verbose_name="نمونه برنامه",
                    ),
                ),
            ],
            options={
                "verbose_name": "منبع برنامه",
                "verbose_name_plural": "منابع برنامه",
            },
        ),
        migrations.CreateModel(
            name="AnalyticsData",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("total_viewers", models.IntegerField(default=0, verbose_name="تعداد کل بینندگان")),
                (
                    "average_rating",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="امتیاز متوسط",
                    ),
                ),
                ("comments_count", models.IntegerField(default=0, verbose_name="تعداد نظرات")),
                ("social_mentions", models.IntegerField(default=0, verbose_name="ذکر در شبکه\u200cهای اجتماعی")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی")),
                (
                    "program_instance",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="programs.programinstance",
                        verbose_name="نمونه برنامه",
                    ),
                ),
            ],
            options={
                "verbose_name": "داده\u200cهای تحلیلی",
                "verbose_name_plural": "داده\u200cهای تحلیلی",
            },
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("schedule_date", models.DateField(verbose_name="تاریخ برنامه\u200cریزی")),
                ("order", models.IntegerField(verbose_name="ترتیب پخش در روز")),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                ("notes", models.TextField(blank=True, verbose_name="یادداشت\u200cهای کنداکتور")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی")),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="programs.channel", verbose_name="شبکه"
                    ),
                ),
                (
                    "program_instance",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule",
                        to="programs.programinstance",
                        verbose_name="نمونه برنامه",
                    ),
                ),
            ],
            options={
                "verbose_name": "برنامه\u200cریزی",
                "verbose_name_plural": "برنامه\u200cریزی\u200cها",
                "ordering": ["schedule_date", "order"],
                "unique_together": {("channel", "schedule_date", "order")},
            },
        ),
        migrations.AddField(
            model_name="conductor",
            name="schedule",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conductor",
                to="programs.schedule",
                verbose_name="برنامه\u200cریزی",
            ),
        ),
        migrations.CreateModel(
            name="ScheduleModification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "modification_type",
                    models.CharField(
                        choices=[
                            ("time_change", "تغییر زمان"),
                            ("cancellation", "لغو"),
                            ("postponement", "تعویق"),
                            ("replacement", "جایگزینی"),
                        ],
                        max_length=20,
                        verbose_name="نوع تعدیل",
                    ),
                ),
                ("reason", models.TextField(verbose_name="دلیل")),
                ("old_start_time", models.DateTimeField(blank=True, null=True, verbose_name="زمان شروع قبلی")),
                ("old_end_time", models.DateTimeField(blank=True, null=True, verbose_name="زمان پایان قبلی")),
                ("new_start_time", models.DateTimeField(blank=True, null=True, verbose_name="زمان شروع جدید")),
                ("new_end_time", models.DateTimeField(blank=True, null=True, verbose_name="زمان پایان جدید")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="تاریخ تعدیل")),
                ("created_by", models.CharField(max_length=100, verbose_name="ایجاد\u200cشده توسط")),
                (
                    "program_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modifications",
                        to="programs.programinstance",
                        verbose_name="نمونه برنامه",
                    ),
                ),
            ],
            options={
                "verbose_name": "تعدیل برنامه\u200cریزی",
                "verbose_name_plural": "تعدیلات برنامه\u200cریزی",
            },
        ),
        migrations.CreateModel(
            name="ProgramGuest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("guest_order", models.IntegerField(default=0, verbose_name="ترتیب ظهور")),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="programs.person", verbose_name="فرد"
                    ),
                ),
                (
                    "program_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guests",
                        to="programs.programinstance",
                        verbose_name="نمونه برنامه",
                    ),
                ),
            ],
            options={
                "verbose_name": "مهمان برنامه",
                "verbose_name_plural": "مهمانان برنامه",
                "unique_together": {("program_instance", "person")},
            },
        ),
        migrations.CreateModel(
            name="ProgramVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("version_number", models.IntegerField(verbose_name="شماره نسخه")),
                ("description", models.TextField(blank=True, verbose_name="توضیحات تغییرات")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد")),
                ("created_by", models.CharField(max_length=100, verbose_name="ایجاد\u200cشده توسط")),
                (
                    "program_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="programs.programinstance",
                        verbose_name="نمونه برنامه",
                    ),
                ),
            ],
            options={
                "verbose_name": "نسخهٔ برنامه",
                "verbose_name_plural": "نسخه\u200cهای برنامه",
                "unique_together": {("program_instance", "version_number")},
            },
        ),
        migrations.CreateModel(
            name="ProgramMember",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_primary", models.BooleanField(default=False, verbose_name="نقش اصلی")),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="programs.person", verbose_name="فرد"
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="programs.program",
                        verbose_name="برنامه",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="programs.role", verbose_name="نقش"
                    ),
                ),
            ],
            options={
                "verbose_name": "عضو برنامه",
                "verbose_name_plural": "اعضای برنامه",
                "unique_together": {("program", "person", "role")},
            },
        ),
    ]
