# Generated by Django 5.2.8 on 2025-11-25 00:18

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("programs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="latitude",
            field=models.FloatField(blank=True, null=True, verbose_name="عرض جغرافیایی"),
        ),
        migrations.AddField(
            model_name="channel",
            name="longitude",
            field=models.FloatField(blank=True, null=True, verbose_name="طول جغرافیایی"),
        ),
        migrations.AddField(
            model_name="channel",
            name="timezone",
            field=models.CharField(blank=True, max_length=64, verbose_name="منطقهٔ زمانی"),
        ),
        migrations.AddField(
            model_name="conductor",
            name="replacement_policy",
            field=models.JSONField(blank=True, default=dict, verbose_name="قوانین جایگزینی"),
        ),
        migrations.AddField(
            model_name="program",
            name="broadcast_type",
            field=models.CharField(
                choices=[
                    ("relay", "رله"),
                    ("live", "زنده"),
                    ("supply", "تأمینی"),
                    ("recorded", "ضبطی"),
                    ("repeat", "تکرار"),
                ],
                default="recorded",
                max_length=20,
                verbose_name="نوع پخش",
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="evaluation_required",
            field=models.BooleanField(default=True, verbose_name="نیازمند ارزیابی"),
        ),
        migrations.AddField(
            model_name="program",
            name="evaluation_status",
            field=models.CharField(
                choices=[("pending", "در انتظار"), ("approved", "تأیید\u200cشده"), ("rejected", "رد شده")],
                default="pending",
                max_length=20,
                verbose_name="وضعیت ارزیابی",
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="fixed_on_clock",
            field=models.BooleanField(default=False, verbose_name="قفل سر ساعت"),
        ),
        migrations.AddField(
            model_name="program",
            name="media_source",
            field=models.CharField(
                choices=[
                    ("automation", "اتوماسیون"),
                    ("studio", "استودیو پخش"),
                    ("relay", "رله شبکه"),
                    ("supply_folder", "پوشه تأمین"),
                ],
                default="automation",
                max_length=30,
                verbose_name="محل پخش",
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, verbose_name="متادیتا"),
        ),
        migrations.AddField(
            model_name="program",
            name="program_origin",
            field=models.CharField(
                choices=[("produced", "تولیدی"), ("live", "زنده"), ("supply", "تأمینی")],
                default="produced",
                max_length=20,
                verbose_name="نوع برنامه",
            ),
        ),
        migrations.AddField(
            model_name="programinstance",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="زمان تأیید"),
        ),
        migrations.AddField(
            model_name="programinstance",
            name="approved_by",
            field=models.CharField(blank=True, max_length=150, verbose_name="تایید\u200cشده توسط"),
        ),
        migrations.AddField(
            model_name="programinstance",
            name="source_folder",
            field=models.CharField(blank=True, max_length=200, verbose_name="پوشه تأمین"),
        ),
        migrations.AddField(
            model_name="programinstance",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="زمان ارسال"),
        ),
        migrations.AddField(
            model_name="programinstance",
            name="submitted_by",
            field=models.CharField(blank=True, max_length=150, verbose_name="ارسال\u200cشده توسط"),
        ),
        migrations.AddField(
            model_name="schedule",
            name="initial_version",
            field=models.BooleanField(default=False, verbose_name="نسخه اولیه"),
        ),
        migrations.AddField(
            model_name="schedule",
            name="locked",
            field=models.BooleanField(default=False, verbose_name="قفل شده"),
        ),
        migrations.AddField(
            model_name="schedule",
            name="updated_version",
            field=models.BooleanField(default=False, verbose_name="نسخه بروز"),
        ),
        migrations.AlterField(
            model_name="program",
            name="default_duration",
            field=models.DurationField(default=datetime.timedelta(seconds=3600), verbose_name="مدت زمان معمولی"),
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("not_approved_1h", "یک ساعت قبل - تایید نشده"),
                            ("manual_change", "تغییر دستی"),
                            ("replacement_used", "جایگزینی استفاده شد"),
                        ],
                        max_length=50,
                        verbose_name="محل تریگر",
                    ),
                ),
                ("recipient_roles", models.JSONField(blank=True, default=list, verbose_name="نقش\u200cهای دریافتی")),
                ("message", models.TextField(verbose_name="متن پیام")),
                (
                    "method",
                    models.CharField(
                        choices=[("ui", "UI"), ("sound", "صدا"), ("email", "ایمیل")],
                        default="ui",
                        max_length=20,
                        verbose_name="روش اعلان",
                    ),
                ),
                ("sent", models.BooleanField(default=False, verbose_name="ارسال شده")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد")),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="programs.schedule",
                        verbose_name="برنامه\u200cریزی",
                    ),
                ),
            ],
            options={
                "verbose_name": "هشدار",
                "verbose_name_plural": "هشدارها",
            },
        ),
        migrations.CreateModel(
            name="Evaluation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_id", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "در انتظار"), ("approved", "تایید"), ("rejected", "رد")],
                        default="pending",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="توضیحات")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="زمان ثبت")),
                ("evaluated_at", models.DateTimeField(blank=True, null=True, verbose_name="زمان ارزیابی")),
                (
                    "content_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"),
                ),
                (
                    "evaluator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="programs.person",
                        verbose_name="ارزیاب",
                    ),
                ),
            ],
            options={
                "verbose_name": "ارزیابی",
                "verbose_name_plural": "ارزیابی\u200cها",
            },
        ),
        migrations.CreateModel(
            name="LiveSegment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200, verbose_name="عنوان آیتم")),
                ("start_offset", models.DurationField(verbose_name="افست شروع")),
                ("duration", models.DurationField(verbose_name="مدت زمان")),
                ("approved", models.BooleanField(default=False, verbose_name="تایید شده")),
                ("notes", models.TextField(blank=True, verbose_name="یادداشت")),
                (
                    "program_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="live_segments",
                        to="programs.programinstance",
                        verbose_name="نمونه برنامه",
                    ),
                ),
            ],
            options={
                "verbose_name": "آیتم زنده",
                "verbose_name_plural": "آیتم\u200cهای زنده",
            },
        ),
        migrations.CreateModel(
            name="ReplacementRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("priority", models.IntegerField(default=50, verbose_name="اولویت")),
                ("candidates", models.ManyToManyField(to="programs.program", verbose_name="نامزدهای جایگزینی")),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replacement_rules",
                        to="programs.schedule",
                        verbose_name="برنامه\u200cریزی",
                    ),
                ),
            ],
            options={
                "verbose_name": "قانون جایگزینی",
                "verbose_name_plural": "قوانین جایگزینی",
            },
        ),
        migrations.CreateModel(
            name="ScheduleTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=150, verbose_name="نام قالب")),
                ("day_of_week", models.IntegerField(verbose_name="روز هفته")),
                ("start_time", models.TimeField(verbose_name="زمان شروع")),
                ("duration", models.DurationField(verbose_name="مدت زمان")),
                ("order", models.IntegerField(verbose_name="ترتیب")),
                ("is_locked", models.BooleanField(default=False, verbose_name="قفل قالب")),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="programs.channel", verbose_name="شبکه"
                    ),
                ),
            ],
            options={
                "verbose_name": "قالب برنامه\u200cریزی",
                "verbose_name_plural": "قالب\u200cهای برنامه\u200cریزی",
            },
        ),
    ]
