# Generated by Django 5.2.8 on 2025-12-01 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0002_channel_latitude_channel_longitude_channel_timezone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="sent_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="زمان ارسال"),
        ),
    ]
