# Generated by Django 5.2.8 on 2025-12-01 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0003_alert_sent_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecipientMapping",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("emails", models.JSONField(blank=True, default=list, verbose_name="ایمیل\u200cهای مستقیم")),
                ("active", models.BooleanField(default=True, verbose_name="فعال")),
                ("persons", models.ManyToManyField(blank=True, to="programs.person", verbose_name="افراد")),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="programs.role", verbose_name="نقش"
                    ),
                ),
            ],
            options={
                "verbose_name": "نگاشت دریافت\u200cکننده",
                "verbose_name_plural": "نگاشت\u200cهای دریافت\u200cکننده",
            },
        ),
    ]
