# Generated by Django 5.2.8 on 2025-12-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0004_recipientmapping"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChannelSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("enable_email", models.BooleanField(default=True, verbose_name="فعال\u200cسازی ایمیل")),
                ("enable_sms", models.BooleanField(default=False, verbose_name="فعال\u200cسازی پیامک")),
                (
                    "default_from_email",
                    models.CharField(blank=True, max_length=200, verbose_name="ایمیل فرستنده پیش\u200cفرض"),
                ),
                (
                    "default_from_number",
                    models.CharField(blank=True, max_length=32, verbose_name="شماره فرستنده پیامک"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی")),
            ],
            options={
                "verbose_name": "تنظیمات کانال\u200cها",
                "verbose_name_plural": "تنظیمات کانال\u200cها",
            },
        ),
        migrations.CreateModel(
            name="E2ERun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "method",
                    models.CharField(
                        choices=[("email", "Email"), ("sms", "SMS"), ("both", "Both")],
                        default="email",
                        max_length=10,
                        verbose_name="روش",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True, verbose_name="شروع")),
                ("finished_at", models.DateTimeField(blank=True, null=True, verbose_name="پایان")),
                ("success", models.BooleanField(default=False, verbose_name="موفق")),
                ("output", models.TextField(blank=True, verbose_name="خروجی")),
            ],
            options={
                "verbose_name": "اجرای E2E",
                "verbose_name_plural": "اجرای E2E",
                "ordering": ("-started_at",),
            },
        ),
        migrations.CreateModel(
            name="E2ESchedule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=150, verbose_name="نام")),
                ("enabled", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "schedule_type",
                    models.CharField(
                        choices=[("hourly", "Hourly"), ("daily", "Daily"), ("weekly", "Weekly")],
                        default="daily",
                        max_length=10,
                        verbose_name="نوع برنامه",
                    ),
                ),
                ("time_of_day", models.TimeField(blank=True, null=True, verbose_name="زمان روز")),
                ("day_of_week", models.IntegerField(blank=True, null=True, verbose_name="روز هفته")),
                (
                    "method",
                    models.CharField(
                        choices=[("email", "Email"), ("sms", "SMS"), ("both", "Both")],
                        default="email",
                        max_length=10,
                        verbose_name="روش",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="ایجاد\u200cشده")),
            ],
            options={
                "verbose_name": "زمان\u200cبندی E2E",
                "verbose_name_plural": "زمان\u200cبندی\u200cهای E2E",
            },
        ),
    ]
